# File: .github/workflows/clone-repo-check.yml

name: Clone Repo Check

on:
  push:
    branches:
      - main

jobs:
  validate-clone:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Clone Test-project Repository
      run: |
        git clone https://github.com/KelvinAbidha/Test-project.git
     
    - name: Verify Clone
      run: |
        if [ -d "Test-project" ]; then
          echo "Repository cloned successfully!"
        else
          echo "Clone verification failed."
          exit 1
