# File: .github/workflows/clone-repo-check.yml

name: Clone Repo Check

on:
  push:
    branches:
      - main

jobs:
  validate-clone:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Clone Test-project Repository
      run: |
        echo "Starting clone operation..."
        git clone https://github.com/KelvinAbidha/Test-project.git || {
          echo "Failed to clone repository. Check the URL or permissions.";
          exit 1;
        }
        ls -l  # List all files in the current directory for debugging
        
    - name: Verify Clone
      run: |
        if [ -d "Test-project" ]; then
          echo "Repository cloned successfully!"
        else
          echo "Clone verification failed. The 'Test-project' directory does not exist."
          exit 1
        fi
